#include "sprites.h"

const Event devents[] = {
    {EXPRESSION_SMILE, NO_CHOICE},
    {EXPRESSION_SMILE, &CHOICE_00},
    {EXPRESSION_SERIOUS, NO_CHOICE},
    {EXPRESSION_SAD, NO_CHOICE},
    {EXPRESSION_HAPPY, NO_CHOICE},
    {EXPRESSION_SMILE, NO_CHOICE},
    {EXPRESSION_SERIOUS, NO_CHOICE},
    {EXPRESSION_SERIOUS, NO_CHOICE},
    {EXPRESSION_SAD, NO_CHOICE},
    {EXPRESSION_SAD, NO_CHOICE},
    {EXPRESSION_CONFUSED, NO_CHOICE},
    {EXPRESSION_HAPPY, NO_CHOICE},
    {EXPRESSION_SMILE, NO_CHOICE},
    {EXPRESSION_SERIOUS, NO_CHOICE},
    {EXPRESSION_CONFUSED, NO_CHOICE},
    {EXPRESSION_SOMEONE, NO_CHOICE},
};