#include "sprites.h"

const Event devents[] = {
    {EXPRESSION_SMILE},
    {EXPRESSION_SMILE},
    {EXPRESSION_SERIOUS},
    {EXPRESSION_SAD},
    {EXPRESSION_HAPPY},
    {EXPRESSION_SMILE},
    {EXPRESSION_SERIOUS},
    {EXPRESSION_SERIOUS},
    {EXPRESSION_SAD},
    {EXPRESSION_SAD},
    {EXPRESSION_CONFUSED},
    {EXPRESSION_HAPPY},
    {EXPRESSION_SMILE},
    {EXPRESSION_SERIOUS},
    {EXPRESSION_CONFUSED},
    {EXPRESSION_SOMEONE}
};